Repository WoWmazon/wowmazon, pull requests merged in 2024-12, with the labels that each got.

#85 ♻️ [WOW-84] refactor : readme 수정
  README.md
  src/components/wish-list/wish-list-product-card.tsx
Labels: docs, refactor

#87 ♻️ [WOW-78] refactor: responsive page
  src/app/layout.tsx
  src/components/common/bottom-sheet.tsx
  src/components/common/simple-bottom-sheet.tsx
  src/components/common/toast.tsx
  src/components/layout/bottom-nav-iconButton.tsx
  src/components/layout/bottom-nav.tsx
  src/components/layout/product-detail-nav.tsx
  src/components/my-page/nickname-edit-form.tsx
  src/components/product-detail/product-detail-content.tsx
  src/components/product-detail/product-detail-header.tsx
  src/components/products/category-drop-down.tsx
  src/components/products/exchage-badge.tsx
  src/components/products/product-list-header.tsx
  src/components/products/product-list.tsx
  src/components/products/productCard.tsx
  src/components/search/search-bar.tsx
  src/components/search/search-container.tsx
  src/components/search/search-recent-keywords.tsx
  src/components/user/preference/allow-authorization.tsx
  src/components/user/sign-up/nickname-fields.tsx
  src/components/wish-list/wish-list-container.tsx
  src/components/wish-list/wish-list-edit-header.tsx
  src/components/wish-list/wish-list-header.tsx
  src/components/wish-list/wish-list-nonecontents.tsx
  src/components/wish-list/wish-list-product-card.tsx
  src/utils/localization/locales/en/user.json
  src/utils/localization/locales/ko/user.json
  tailwind.config.ts
Labels: design, refactor

#88 ➕ [WOW-87] feat : 동적/정적 메타데이터 설정 및 오픈그래프 설정
  public/images/noImage.svg
  public/images/og/open-graph.png
  src/app/[locale]/auth/sign-in/page.tsx
  src/app/[locale]/product-detail/[id]/page.tsx
  src/app/actions.ts
  src/app/layout.tsx
  src/assets/images/nito-big.svg
  src/css/tailwind.css
  src/utils/device-utils.ts
  src/utils/metadata-utils.ts
  src/utils/register-utils.ts
Labels: remove, feat, fix, refactor

#89 🔧 [WOW-88] fix: signin recent reset
  src/api/user/apis.ts
  src/auth/token.ts
  src/hooks/useUserQuery.ts
Labels: fix

#92 ♻️ [WOW-89] refactor: reponsive v2
  src/app/layout.tsx
  src/components/common/bottom-sheet.tsx
  src/components/common/simple-bottom-sheet.tsx
  src/components/common/toast.tsx
  src/components/layout/bottom-nav.tsx
  src/components/layout/product-detail-nav.tsx
  src/components/product-detail/product-detail-content.tsx
  src/components/product-detail/product-detail-header.tsx
  src/components/search/search-bar.tsx
  src/components/wish-list/wish-list-container.tsx
  src/components/wish-list/wish-list-edit-header.tsx
Labels: design, refactor

#94 ➕ [WOW-90] feat : bottom-nav 다국어 처리 기능 추가
  src/components/layout/bottom-nav-iconButton.tsx
  src/constants/bottom-nav-button.ts
  src/utils/localization/locales/en/common.json
  src/utils/localization/locales/ko/common.json
Labels: feat
