Repository WoWmazon/wowmazon, pull requests merged in 2024-11, with the labels that each got.

#60 ♻️ [Wow-56] refactor : 공통컴포넌트 modal, bottomSheet에 zustand 적용
  src/components/common/bottom-sheet.tsx
  src/components/common/modal.tsx
  src/components/common/simple-bottom-sheet.tsx
  src/components/common/types.d.ts
  src/components/test-button.tsx
  src/components/user/sign-up/close-modal.tsx
  src/components/user/sign-up/signup-container.tsx
  src/stores/common/stores.ts
  src/stores/common/type.d.ts
Labels: refactor

#62 ➕ [WOW-62] feat: product card skeleton 추가
  src/app/[locale]/(main)/test-page/page.tsx
  src/components/skeletons/product-card-skeleton.tsx
  src/css/index.css
  src/css/skeleton.css
Labels: feat

#61 ♻️ [WOW-53] feat & refactor : product detail nav UI 및 product detail 리팩토링
  src/app/[locale]/product-detail/[id]/page.tsx
  src/app/[locale]/product-detail/layout.tsx
  src/components/layout/product-detail-nav.tsx
  src/components/product-detail/product-detail-content.tsx
  src/components/product-detail/product-detail-header.tsx
  src/components/product-detail/product-price-info.tsx
  src/components/product-detail/related-product-card.tsx
  src/components/product-detail/related-product.tsx
  src/components/products/exchage-badge.tsx
  src/components/products/productCard.tsx
  src/components/products/types.d.ts
  src/utils/exchange.ts
Labels: feat, refactor

#63 [WOW-57] product-list 무한스크롤 적용
  src/api/product/apis.ts
  src/app/[locale]/(main)/product-list/page.tsx
  src/components/products/product-List.tsx
  src/constants/query-keys.ts
  src/hooks/useInfiniteProductList.ts
  src/hooks/useIntersectionObserver.tsx
Labels: remove, feat, refactor

#59 ➕ [WOW-54] feat: search page
  src/api/product/apis.ts
  src/api/product/queries.ts
  src/app/layout.tsx
  src/app/providers.tsx
  src/components/products/types.d.ts
  src/components/search/recent-search-item.tsx
  src/components/search/recent-search-keyword-item.tsx
  src/components/search/recent-search-keyword.tsx
  src/components/search/recent-search.tsx
  src/components/search/search-container.tsx
  src/components/search/search-filter.tsx
  src/components/search/search-header.tsx
  src/components/search/search-result.tsx
  src/components/search/text-button.tsx
  src/components/search/types.d.ts
  src/constants/query-keys.ts
  src/hooks/useDebounce.tsx
  src/stores/search/stores.ts
  src/stores/search/types.d.ts
  src/utils/apis/create-query-string.ts
Labels: feat, fix, refactor

#64 ♻️ [Wow-65] refactor: search page refactor
  src/api/product/queries.ts
  src/components/search/search-bar.tsx
  src/components/search/search-container.tsx
  src/components/search/search-filter.tsx
  src/components/search/search-recent-keyword-item.tsx
  src/components/search/search-recent-keywords.tsx
  src/components/search/search-result.tsx
  src/components/search/types.d.ts
  src/components/skeletons/product-card-skeleton.tsx
  src/components/user/sign-up/nickname-fields.tsx
  src/stores/search/stores.ts
  src/stores/search/types.d.ts
Labels: fix, refactor

#68 [WOW-67] refactor : api 요청전 유효한토큰으로 미리갱신하는 함수 생성 및 미들웨어 설정 수정
  next.config.mjs
  package-lock.json
  package.json
  src/api/fetchApi.ts
  src/app/actions.ts
  src/auth/token.ts
  src/components/product-detail/related-product-card.tsx
  src/components/product-detail/related-product.tsx
  src/components/product-detail/type.d.ts
  src/components/products/exchage-badge.tsx
  src/components/products/product-list.tsx
  src/components/search/types.d.ts
  src/hooks/useInfiniteCategoryId.tsx
  src/hooks/useInfiniteProductList.ts
  src/middleware.ts
  src/utils/get-cookie.ts
  src/utils/set-cookie.ts
Labels: remove, feat, fix, refactor

#69 ➕ [WOW-71] product-list 페이지에 카테고리 및 필터 기능 추가
  src/components/products/product-list-category-filter.tsx
  src/components/products/product-list.tsx
  src/components/products/types.d.ts
  src/components/search/search-bar.tsx
  src/components/search/search-container.tsx
  src/components/search/search-filter.tsx
  src/components/search/search-recent-keyword-item.tsx
  src/components/search/search-recent-keywords.tsx
  src/hooks/useInfiniteCategoryId.ts
  src/hooks/useIntersectionObserver.ts
  src/stores/prooduct/stores.ts
  src/stores/prooduct/types.d.ts
Labels: feat, refactor, rename

#70 ♻️ [WOW-72] refactor: search refactor v2
  src/api/product/apis.ts
  src/api/product/queries.ts
  src/components/products/types.d.ts
  src/components/search/search-bar.tsx
  src/components/search/search-container.tsx
  src/components/search/search-recent-keyword-item.tsx
  src/components/search/search-recent-keywords.tsx
  src/components/search/search-result.tsx
  src/components/search/types.d.ts
  src/hooks/useInfiniteProductList.ts
  src/stores/prooduct/stores.ts
  src/stores/prooduct/types.d.ts
Labels: refactor

#72 ➕ [WOW-73] 선택한 카테고리 항목으로 가는 자동 스크롤 기능 추가 및 가로스크롤 제거
  src/components/common/custom-checkbox.tsx
  src/components/products/category-drop-down-button.tsx
  src/components/products/category-drop-down.tsx
Labels: feat, refactor

#71 ♻️ WOW-74 refactor : 공통 컴포넌트 toast zustand로 변경
  src/app/[locale]/product-detail/[id]/page.tsx
  src/components/common/toast.tsx
  src/components/common/types.d.ts
  src/components/layout/product-detail-nav.tsx
  src/components/product-detail/related-product-card.tsx
  src/components/test-button.tsx
  src/components/test/test-components.tsx
  src/stores/common/stores.ts
  src/stores/common/type.d.ts
Labels: refactor

#74 ♻️ [WOW-75] bottom-nav url path 수정 (새로고침시에도 활성화 유지 및 페이지 이동 수정)
  src/components/layout/bottom-nav-iconButton.tsx
  src/components/layout/bottom-nav.tsx
  src/middleware.ts
Labels: feat, refactor

#73 ♻️ [WOW-69] refactor: toast refactor
  src/components/common/toast.tsx
  src/components/test/test-components.tsx
  src/stores/common/stores.ts
Labels: fix, refactor

#76 🔧 [WOW-77] fix:search-page와 product-list의 데이터 문제 해결
  src/components/products/product-list-category-filter.tsx
  src/components/search/search-container.tsx
  src/stores/prooduct/stores.ts
Labels: fix

#78 ♻️ [WOW-80] refactor: search reset
  src/components/products/product-list-category-filter.tsx
  src/components/search/search-bar.tsx
  src/components/search/search-container.tsx
  src/components/search/search-recent-keyword-item.tsx
  src/components/search/search-result.tsx
  src/stores/prooduct/types.d.ts
Labels: refactor

#79 ♻️ [WOW-81] refactor: toast refactor
  src/components/common/toast.tsx
Labels: refactor

#80 ➕ [WOW-75] feat : bottom nav +버튼 기능 추가
  src/api/product/apis.ts
  src/assets/icons/addProduct.svg
  src/assets/icons/amazon_icon.svg
  src/assets/icons/link-icon.svg
  src/components/layout/bottom-nav.tsx
  src/components/layout/bottom-sheet-add-link.tsx
  src/components/layout/bottom-sheet-add-products.tsx
  src/components/layout/types.d.ts
  src/providers/query-provider.tsx
Labels: design, feat, refactor

#81 ➕ [WOW-83] feat : product list skeleton 및 prefetch 기능 추가
  src/app/[locale]/(main)/product-list/page.tsx
  src/components/products/product-list.tsx
  src/components/search/search-result.tsx
  src/components/skeletons/product-card-skeleton.tsx
  src/components/skeletons/search-filter-skeleton.tsx
Labels: feat, refactor

#83 ♻️ WOW-79 refactor : product 관련 리팩토링
  src/api/exchange/apis.ts
  src/app/[locale]/(main)/product-list/page.tsx
  src/components/product-detail/product-detail-container.tsx
  src/components/product-detail/product-detail-content.tsx
  src/components/product-detail/product-price-info.tsx
  src/components/product-detail/related-product-card.tsx
  src/components/product-detail/related-product.tsx
  src/components/product-detail/types.d.ts
  src/components/products/exchage-badge.tsx
  src/components/products/product-list-category-filter.tsx
  src/components/products/product-list-header.tsx
  src/components/products/product-list.tsx
  src/components/products/productCard.tsx
  src/components/products/types.d.ts
  src/components/search/search-result.tsx
  src/components/wish-list/types.d.ts
  src/components/wish-list/wish-list-container.tsx
  src/components/wish-list/wish-list-header.tsx
  src/components/wish-list/wish-list.tsx
  src/hooks/useFavoriteProduct.ts
  src/utils/exchange.ts
Labels: fix, refactor

#84 📝 [WOW-84] docs : readme.md 생성
  README.md
Labels: docs
