Repository WoWmazon/wowmazon, pull requests merged in 2024-10, with the labels that each got.

#6 ➕ WOW-14 feat: github PR description template 설정
  .github/pull_request_template.md
  .github/workflows/review.yml
Labels: feat

#10 Update nextjs.yml
  .github/workflows/nextjs.yml
Labels: setting

#12 Update nextjs.yml
  .github/workflows/nextjs.yml
Labels: refactor

#16 ➕ [WOW-21] feat : color 디자인 시스템 파일 생성
  .github/workflows/nextjs.yml
  src/app/layout.tsx
  src/components/common/radio.tsx
  src/css/color.ts
  tailwind.config.ts
Labels: design, feat

#17 ➕ [WOW-21] feat : color 디자인 시스템 파일 생성
  .github/workflows/nextjs.yml
  src/app/layout.tsx
  src/components/common/radio.tsx
Labels: design, feat

#18 Revert "➕ [WOW-21] feat : color 디자인 시스템 파일 생성 "
  .github/workflows/nextjs.yml
  src/app/layout.tsx
  src/components/common/radio.tsx
  src/css/color.ts
  tailwind.config.ts
Labels: revert

#19 Revert "➕ [WOW-21] feat : color 디자인 시스템 파일 생성 "
  .github/workflows/nextjs.yml
  src/app/layout.tsx
  src/components/common/radio.tsx
Labels: revert

#21 ➕ [WOW-21] feat : color 디자인 시스템 파일 생성
  src/css/color.ts
  tailwind.config.ts
Labels: fix

#15 💄 [WOW-18] design : icons 폴더, svg파일 추가
  src/assets/icons/addProduct.svg
  src/assets/icons/addProduct_gray.svg
  src/assets/icons/alarm.svg
  src/assets/icons/closeButton.svg
  src/assets/icons/detail_export.svg
  src/assets/icons/detail_noProduct.svg
  src/assets/icons/detail_prepareImage.svg
  src/assets/icons/detail_trash.svg
  src/assets/icons/header_alarm.svg
  src/assets/icons/header_alarm_redDot.svg
  src/assets/icons/header_arrow.svg
  src/assets/icons/logo_red.svg
  src/assets/icons/logo_white.svg
  src/assets/icons/mypage_rename.svg
  src/assets/icons/mypage_social_apple.svg
  src/assets/icons/mypage_social_google.svg
  src/assets/icons/nav_mypage_gray.svg
  src/assets/icons/nav_mypage_red.svg
  src/assets/icons/nav_productList_gray.svg
  src/assets/icons/nav_productList_red.svg
  src/assets/icons/nav_search_gray.svg
  src/assets/icons/nav_search_red.svg
  src/assets/icons/nav_wishList_gray.svg
  src/assets/icons/nav_wishList_red.svg
  src/assets/icons/product_alarmOff.svg
  src/assets/icons/product_alarmOn.svg
  src/assets/icons/product_amazon.svg
  src/assets/icons/product_link.svg
  src/assets/icons/restock_alarmOff.svg
  src/assets/icons/restock_alarmOn.svg
  src/assets/icons/share.svg
Labels: design

#22 💄 [WOW-19] design : woff 파일 추가 및 기본 폰트 설정
  public/fonts/Pretendard-Bold.woff
  public/fonts/Pretendard-Regular.woff
  src/app/layout.tsx
  src/css/fonts.ts
  src/css/index.css
  src/css/tailwind.css
  tailwind.config.ts
Labels: design

#14 ➕ [WOW-20] feat: radio, checkbox, toggle common components 추가
  README.md
  src/app/layout.tsx
  src/assets/icons/check-lg.svg
  src/assets/icons/check-sm.svg
  src/assets/icons/circle-lg.svg
  src/assets/icons/circle-sm.svg
  src/components/common/custom-checkbox.tsx
  src/components/common/custom-radio.tsx
  src/components/common/custom-toggle.tsx
  src/components/common/radio.tsx
  src/components/common/types.d.ts
  src/css/tailwind.css
Labels: feat, refactor

#23 📌 [WOW-23] setting : i18n, react-hook-form, react query 라이브러리 추가
  package-lock.json
  package.json
Labels: setting

#24 💄 [WOW-12] design : frame size setting
  src/app/layout.tsx
  src/app/page.tsx
Labels: design

#25 📌 [WOW-24] setting : i18n 다국어처리
  package-lock.json
  package.json
  src/app/[locale]/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/locale-button.tsx
  src/middleware.ts
  src/utils/localization/client.ts
  src/utils/localization/locales/en/common.json
  src/utils/localization/locales/ko/common.json
  src/utils/localization/server.ts
  src/utils/localization/settings.ts
Labels: setting

#28 ➕ [WOW-25] feat : common iconbutton 및 typeGuard 생성
  src/components/common/custom-icon-button.tsx
  src/components/common/types.d.ts
  src/utils/type-guard.ts
Labels: design, feat

#27 ➕ [WOW-26] feat: input-delete-button.svg 추가, custom-input 추가.
  src/assets/icons/input-delete-button.svg
  src/components/common/custom-checkbox.tsx
  src/components/common/custom-input.tsx
  src/components/common/custom-radio.tsx
  src/components/common/custom-toggle.tsx
  src/components/common/types.d.ts
Labels: design, feat, refactor

#32 📌 [WOW-32] setting : main page 경로 setting
  src/app/[locale]/(main)/mypage/page.tsx
  src/app/[locale]/(main)/product-list/page.tsx
  src/app/[locale]/(main)/search/page.tsx
  src/app/[locale]/(main)/wish-list/page.tsx
Labels: setting

#31 ➕ [WOW-29] feat : common badge
  src/assets/icons/badge_arrow_down.svg
  src/assets/icons/badge_arrow_up.svg
  src/components/common/badge.tsx
  src/components/common/types.d.ts
  src/css/color.ts
  src/utils/localization/locales/en/common.json
  src/utils/localization/locales/ko/common.json
Labels: design, feat

#34 ♻️ [WOW-33] refeactor : middleware 수정
  src/middleware.ts
Labels: refactor

#30 ➕ [WOW-28] feat : modal 컴포넌트 추가 및 metadata 변경, favicon 적용
  public/favicon.svg
  src/app/[locale]/page.tsx
  src/app/layout.tsx
  src/assets/icons/wifiSlash.svg
  src/components/common/custom-button.tsx
  src/components/common/modal.tsx
  src/components/common/types.d.ts
  src/components/test-button.tsx
  src/css/color.ts
  src/utils/localization/locales/en/common.json
  src/utils/localization/locales/ko/common.json
Labels: design, feat, setting

#36 ♻️ [Wow-37] refactor: layout refactoring
  src/app/layout.tsx
  src/assets/images/main-mid.png
  src/components/common/toast.tsx
Labels: fix, refactor

#35 ♻️ [WOW-34] refactor: custom-input 리팩토링
  src/app/[locale]/page.tsx
  src/components/common/custom-input.tsx
  src/components/common/toast.tsx
  src/components/common/types.d.ts
  src/components/test/test-components.tsx
Labels: refactor

#37 ➕ [WOW-35] feat : wish list 페이지 생성
  src/app/[locale]/(main)/wish-list/page.tsx
  src/components/wish-list/types.d.ts
  src/components/wish-list/wish-list-header.tsx
  src/components/wish-list/wish-list-nonecontents.tsx
  src/utils/localization/locales/en/common.json
  src/utils/localization/locales/ko/common.json
Labels: design

#38 📝 [WOW-39] rename : test page 생성 및 폴더구조/폴더명 수정
  src/app/[locale]/(main)/layout.tsx
  src/app/[locale]/(main)/my-page/page.tsx
  src/app/[locale]/(main)/test-page/page.tsx
  src/app/[locale]/(main)/wish-list/page.tsx
  src/app/[locale]/page.tsx
  src/app/layout.tsx
  src/app/types.d.ts
  src/components/wish-list/wish-list-nonecontents.tsx
  tsconfig.json
Labels: rename

#39 [WOW-36] feat : bottom nav 컴포넌트 생성
  src/app/[locale]/(main)/layout.tsx
  src/app/[locale]/(main)/wish-list/page.tsx
  src/app/[locale]/page.tsx
  src/components/layout/bottom-nav-iconButton.tsx
  src/components/layout/bottom-nav.tsx
  src/components/layout/types.d.ts
  src/components/wish-list/wish-list-header.tsx
  src/components/wish-list/wish-list-nonecontents.tsx
  src/constants/bottom-nav-button.ts
  src/utils/localization/locales/en/common.json
  src/utils/localization/locales/en/wish-list.json
  src/utils/localization/locales/ko/common.json
  src/utils/localization/locales/ko/wish-list.json
Labels: design, feat

#41 ➕ [WOW-38] feat : bottom sheet 추가
  src/app/[locale]/(main)/layout.tsx
  src/app/[locale]/(main)/test-page/page.tsx
  src/app/layout.tsx
  src/components/common/bottom-sheet.tsx
  src/components/common/simple-bottom-sheet.tsx
  src/components/common/types.d.ts
  src/components/layout/bottom-nav.tsx
  src/components/test-button.tsx
  src/css/globals.css
  src/utils/localization/locales/en/common.json
  src/utils/localization/locales/ko/common.json
Labels: design, feat

#40 ➕ [Wow-31] feat: 로그인 / 회원가입 추가
  src/api/user/apis.ts
  src/app/[locale]/auth/layout.tsx
  src/app/[locale]/auth/preference/page.tsx
  src/app/[locale]/auth/sign-in/page.tsx
  src/app/[locale]/auth/sign-up/page.tsx
  src/app/actions.ts
  src/app/api/user/login/route.ts
  src/app/api/user/nickname/route.ts
  src/app/api/user/refresh/route.ts
  src/app/api/user/register/route.ts
  src/app/api/user/validate/route.ts
  src/app/types.d.ts
  src/assets/icons/right_arrow.svg
  src/assets/images/nito-big.svg
  src/components/common/custom-checkbox.tsx
  src/components/user/preference/allow-authorization.tsx
  src/components/user/preference/choose-language.tsx
  src/components/user/preference/preference-container.tsx
  src/components/user/preference/types.d.ts
  src/components/user/sign-up/check-fields.tsx
  src/components/user/sign-up/check-item.tsx
  src/components/user/sign-up/close-modal.tsx
  src/components/user/sign-up/handlers.ts
  src/components/user/sign-up/nickname-fields.tsx
  src/components/user/sign-up/signup-container.tsx
  src/components/user/sign-up/types.d.ts
  src/constants/api-urls.ts
  src/constants/nito-urls.ts
  src/constants/user.ts
  src/css/color.ts
  src/css/tailwind.css
  src/middleware.ts
  src/utils/cookie.ts
  src/utils/deviceUtils.ts
  src/utils/localization/locales/en/user.json
  src/utils/localization/locales/ko/user.json
  src/utils/registerUtils.ts
Labels: feat, refactor

#42 ➕ [Wow-43] feat: serach page UI
  src/app/[locale]/(main)/search/page.tsx
  src/components/search/recent-search-keyword-item.tsx
  src/components/search/recent-search-keyword.tsx
  src/components/search/search-filter.tsx
  src/components/search/search-header.tsx
  src/components/search/search-none-product.tsx
  src/components/search/search-result.tsx
  src/components/search/text-button.tsx
  src/components/search/types.d.ts
Labels: feat, refactor

#43 ➕ [WOW-41] feat : 상품 상세 페이지 UI
  src/app/[locale]/(main)/product-detail/page.tsx
  src/assets/images/grahp.jpg
  src/assets/images/headset.jpg
  src/components/product-detail/product-detail-content.tsx
  src/components/product-detail/product-detail-header.tsx
  src/components/product-detail/related-product.tsx
Labels: feat

#44 [WOW-40] feat : product list components
  next.config.mjs
  src/api/product/apis.ts
  src/app/[locale]/(main)/product-list/page.tsx
  src/app/[locale]/(main)/product-list/types.d.ts
  src/components/common/badge.tsx
  src/components/common/types.d.ts
  src/components/products/productCard.tsx
  src/components/products/productList.tsx
  src/components/products/types.d.ts
Labels: design, feat

#45 [W OW-45] refactor : api 함수
  src/api/fetchApi.ts
  src/api/product/apis.ts
  src/api/user/apis.ts
  src/app/[locale]/(main)/product-list/page.tsx
  src/app/actions.ts
  src/components/products/product-List.tsx
  src/components/products/productCard.tsx
  src/utils/apis/create-URL-Params.ts
Labels: refactor, rename

#48 ♻️ [WOW-41] refactor : product detail content 컴포넌트 분리 및 API 연결, fetchAPI.ts 함수 수정
  src/api/fetchApi.ts
  src/api/product/apis.ts
  src/app/[locale]/(main)/product-detail/page.tsx
  src/app/[locale]/(main)/product-list/types.d.ts
  src/assets/images/noImage.svg
  src/components/product-detail/product-detail-content.tsx
  src/components/product-detail/product-detail-header.tsx
  src/components/product-detail/product-price-graph.tsx
  src/components/product-detail/product-price-info.tsx
  src/components/product-detail/related-product.tsx
  src/components/product-detail/type.d.ts
  src/components/products/product-List.tsx
  src/components/products/types.d.ts
  src/components/search/search-container.tsx
  src/providers/query-provider.tsx
Labels: feat, refactor

#52 🔧 [WOW-55] fix: image warning
  src/assets/icons/nav_mypage_gray.svg
  src/assets/icons/nav_mypage_red.svg
  src/assets/icons/nav_productList_gray.svg
  src/assets/icons/nav_productList_red.svg
  src/assets/icons/nav_search_gray.svg
  src/assets/icons/nav_search_red.svg
  src/assets/icons/nav_wishList_gray.svg
  src/assets/icons/nav_wishList_red.svg
  src/assets/icons/product_default_img.svg
  src/components/products/productCard.tsx
Labels: design

#53 ➕ [WOW-48] product-list-exchangeBadge 생성
  package-lock.json
  package.json
  src/api/exchange/apis.ts
  src/api/product/apis.ts
  src/app/[locale]/(main)/product-list/page.tsx
  src/app/[locale]/(main)/product-list/types.d.ts
  src/components/products/exchage-badge.tsx
  src/components/products/product-List.tsx
  src/components/products/product-list-header.tsx
  src/components/products/types.d.ts
  src/utils/date.ts
Labels: design, feat

#51 ➕ [Wow-52] feat: 상품 상세 > 해당 상품과 비슷한 상품 UI
  src/api/product/apis.ts
  src/app/[locale]/product-detail/[id]/page.tsx
  src/app/[locale]/product-detail/layout.tsx
  src/components/layout/product-detail-nav.tsx
  src/components/product-detail/related-product-card.tsx
  src/components/product-detail/related-product.tsx
Labels: feat, refactor

#50 ➕ [Wow-51] feat: mypage UI
  src/app/[locale]/(main)/my-page/page.tsx
  src/components/common/custom-checkbox.tsx
  src/components/common/custom-radio.tsx
  src/components/common/custom-toggle.tsx
  src/components/my-page/my-page-header.tsx
  src/components/my-page/my-page-info.tsx
  src/components/my-page/my-page-notification-setting.tsx
  src/components/my-page/my-page-withdrawal.tsx
  src/components/my-page/types.d.ts
Labels: feat

#47 ♻️ [Wow-46] refactor: user refactoring
  src/api/fetchApi.ts
  src/api/user/apis.ts
  src/app/actions.ts
  src/app/api/user/login/route.ts
  src/app/api/user/nickname/route.ts
  src/app/api/user/refresh/route.ts
  src/app/api/user/register/route.ts
  src/app/api/user/validate/route.ts
  src/components/user/sign-up/check-fields.tsx
  src/components/user/sign-up/handlers.ts
  src/components/user/sign-up/nickname-fields.tsx
  src/components/user/sign-up/signup-container.tsx
  src/components/user/sign-up/types.d.ts
  src/constants/api-urls.ts
  src/constants/nito-urls.ts
  src/constants/user.ts
  src/middleware.ts
Labels: refactor

#57 📌 setting : Update git-push.yml
  .github/workflows/git-push.yml
Labels: setting

#58 📌 setting : Update git-push.yml
  .github/workflows/git-push.yml
Labels: setting
